[project]
name = "tutorial-browser-use"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "browser-use>=0.1.41",
    "langchain-core>=0.3.49",
    "pytest-playwright>=0.7.0",
]
